name: First Workflow
on: workflow_dispatch
jobs: 
  first_jobs:
    runs-on: ubuntu-latest
    steps: 
      - name: print greeting 
        run: echo "hello buddy"
      - name: print goodbye
        run: echo "done-bye"
      
